name: 'ci'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  unit-test:
    # let's ignore release commits, otherwise it'll try to run twice
    if: |
      !startsWith(github.event.head_commit.message , 'chore(release):') && 
      !startsWith(github.event.head_commit.message , 'docs')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set node version to latest
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'

      - run: pnpm install

      - name: Run typecheck
        run: npm run typecheck

      - name: Run unit tests
        run: npm run test

      - name: Run build
        run: npm run build

